[package]
name = "fastvk"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["rt", "net", "macros", "rt-multi-thread", "sync"] }
crossbeam-channel = "0.5"
dotenv = "0.15.0"
futures = "0.3.21"
thiserror = "1.0.32"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3